### ISSUE TITLE
Problems with Unzip

### ISSUE THREAD

**Issue by Elencon** [nirbar/PanelSwWixExtension#3]
Shalom.
During Install with Wix i need to unpack zip file  with multiple files in subfolders.
I started with ZipFileUT project 
In Visual Studio 2019 I created "Setup project for Wix v3", added reference to WixUtilExtension and package PanelSwWixExtension.
I took files  SizeZero.txt and Product.wxs from UnitTests/ZipFileUT/
Made minor changes in Product attributes:
  <Product Id="{769C11E5-D811-4CE3-BE79-CC23725E6B38}" Name="ZipFileUT" Language="1033" Version="1.0.0.0" Manufacturer="Eneriqs Ltd" UpgradeCode="{8DC7207F-59B4-45E6-90B0-75769F8040B8}">
Built 
There were no errors
I got 3 files :
cab1.cab
ZipFileUT.msi
ZipFileUT.wixpdb
After Right click Install I get in folder
C:\Program Files (x86)\UnitTestSetup
Empty zip file 1.zip
When I try to uninstall I get messageBox with "This action only valid for products that are currently installed"
What is going wrong ?
I enclose 
[myLog.txt](https://github.com/nirbar/PanelSwWixExtension/files/6383738/myLog.txt)
Log file
[myLog.txt](https://github.com/nirbar/PanelSwWixExtension/files/6383730/myLog.txt)

**Comment by nirbar** [comment]
@Elencon, thanks for reporting this.
I wasn't able to reproduce it
The log file says "System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: 1 is not a supported code page."
Which points to a known issues in SharpZipLib: https://github.com/icsharpcode/SharpZipLib/issues/195

I fixed by setting a default code page. Please use v2.31.3 which should be available in nuget.org shortly

**Comment by Elencon** [comment]
Thank you for quick response

**Comment by Elencon** [comment]
It works thanks
